
# THIS CONFIG FILE IS EXAMPLE

[cfg.main_app]
port = 1234
users_fs_path = "/ur/abs/path/to/users_fs"
web_static_path = "/ur/abs/path/to/web_static"
hashed_links_len = 6
max_folder_size_to_be_downloadable = 2_000 # in MB

jwt_secret = "secret???"
password_hash_secret = "secret???"


[cfg.database]
host = "localhost"
port = 27017
db_name = "tiny-cloud-db"
password = "password???"


[cfg.new_user]
default_space_available = 10_000 # in MB
default_user_img_name = "default-user-img.png"
