
[cfg.main_app]
port = 1400
users_fs_path = "/home/qwerty/my-projects/tiny-cloud/USERS_FS"

jwt_secret = "idontwannathinkhere"
password_hash_secret = "idontwannathinkhere"


[cfg.database]
host = "localhost"
port = 27017
db_name = "tiny-cloud-db"
password = "idontwannathinkhere"


[cfg.new_user]
default_space_available = 10_000 # in MB
default_user_img_name = "default-user-img.png"